-- Create ping table
CREATE TABLE IF NOT EXISTS ping (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  status TEXT,
  http_code INTEGER,
  response_time_ms INTEGER,
  error_message TEXT,
  triggered_by TEXT
);

-- Enable Row Level Security for ping
ALTER TABLE ping ENABLE ROW LEVEL SECURITY;

-- Allow public insert to ping (for health checks)
CREATE POLICY "Allow public insert to ping" ON ping
  FOR INSERT WITH CHECK (true);

-- Allow public select from ping (for displaying status)
CREATE POLICY "Allow public select from ping" ON ping
  FOR SELECT USING (true);


-- Create web_vitals table
CREATE TABLE IF NOT EXISTS web_vitals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  name TEXT,
  value NUMERIC,
  rating TEXT,
  delta NUMERIC,
  navigation_type TEXT
);

-- Enable Row Level Security for web_vitals
ALTER TABLE web_vitals ENABLE ROW LEVEL SECURITY;

-- Allow public insert to web_vitals (for collecting metrics)
CREATE POLICY "Allow public insert to web_vitals" ON web_vitals
  FOR INSERT WITH CHECK (true);

-- Allow public select from web_vitals (for analytics dashboard)
CREATE POLICY "Allow public select from web_vitals" ON web_vitals
  FOR SELECT USING (true);
