name: Vercel Production Deployment

# 환경변수 세팅
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PRJ_ID }}

on:
  push:
    branches: ['master']

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Vercel CLI
        run: |
          export PNPM_HOME="/home/runner/.local/share/pnpm"
          export PATH="$PNPM_HOME:$PATH"
          pnpm add -g vercel@canary

      - name: Pull Vercel Environment Information
        run: |
          export PNPM_HOME="/home/runner/.local/share/pnpm"
          export PATH="$PNPM_HOME:$PATH"
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: |
          export PNPM_HOME="/home/runner/.local/share/pnpm"
          export PATH="$PNPM_HOME:$PATH"
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: |
          export PNPM_HOME="/home/runner/.local/share/pnpm"
          export PATH="$PNPM_HOME:$PATH"
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
